"""add_search_vector_to_chunks

Revision ID: 40cedbe3da8b
Revises: 02a1b2c3d4e5
Create Date: 2026-04-05 21:05:57.288740

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40cedbe3da8b"
down_revision: str | Sequence[str] | None = "02a1b2c3d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "ix_chunks_search_vector",
        "chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunks_search_vector", table_name="chunks", postgresql_using="gin"
    )
    op.drop_column("chunks", "search_vector")
    # ### end Alembic commands ###
