"""Make chunk embedding dimensions dynamic

Revision ID: e4f2533ea402
Revises: 40cedbe3da8b
Create Date: 2026-04-05 23:04:13.881204

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e4f2533ea402"
down_revision: str | Sequence[str] | None = "40cedbe3da8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
